tasks:
  - init: mysqladmin -u root password 'gitpod' && composer create-project
      phpmyadmin/phpmyadmin && composer create-project --prefer-dist
      laravel/laravel
image:
  file: .gitpod.Dockerfile
